name: "tabular_model"
backend: "python"
max_batch_size: 16

input [
  {
    name: "age"
    data_type: TYPE_FP32
    dims: [1]
  },
  {
    name: "income"
    data_type: TYPE_FP32
    dims: [1]
  },
  {
    name: "gender"
    data_type: TYPE_STRING
    dims: [1]
  }
]

output [
  {
    name: "PRED_LABEL"
    data_type: TYPE_STRING
    dims: [1]
  }
]


# name: "PRED_VALUE"
# data_type: TYPE_FP32
# dims: [1]


instance_group [
  {
    count: 1
    kind: KIND_GPU
    gpus: [0]
  }
]

