name: "model1"
backend: "onnxruntime"
max_batch_size: 16
input [
  {
    name: "input"
    data_type: TYPE_FP32
    dims: [192]
  }
]
output [
  {
    name: "output"
    data_type: TYPE_FP32
    dims: [1]
  }
]
instance_group [
  {
    count: 1
    kind: KIND_GPU
    gpus: [0]
  }
]
